Project/Controllers/Frontend/AuthorBlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers.Frontend
{
    public class AuthorBlogsController : Controller
    {
        private BLOGEntities db = new BLOGEntities();

        // GET: AuthorBlogs
        public ActionResult Index()
        {
            var blogs = db.Blogs.Include(b => b.Authors).Include(b => b.Categories);
            return View(blogs.ToList());
        }

        // GET: AuthorBlogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blogs blogs = db.Blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            return View(blogs);
        }

        // GET: AuthorBlogs/Create
        public ActionResult Create()
        {
            ViewBag.category = db.Categories.ToList();

            return View();
        }

        // POST: AuthorBlogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Blogs blog, HttpPostedFileBase image)
        { //ben de bilmiyorum ki çalışıyrdu :( bak hatta admin kısmından kaydedelim 
            try
            {
                if (image != null)
                {
                    WebImage webImage = new WebImage(image.InputStream);
                    FileInfo fileInfo = new FileInfo(image.FileName);
                    string newImage = Guid.NewGuid().ToString() + fileInfo.Extension;
                    webImage.Resize(800, 350);
                    webImage.Save("~/Uploads/" + newImage);
                    blog.image = "/Uploads/" + newImage;
                }
                blog.blogDate = DateTime.Now;
                db.Blogs.Add(blog);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AuthorBlogs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blogs blogs = db.Blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "name", blogs.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "title", blogs.CategoryID);
            return View(blogs);
        }

        // POST: AuthorBlogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BlogID,title,text,image,CategoryID,AuthorID,blogDate")] Blogs blogs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(blogs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "name", blogs.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "title", blogs.CategoryID);
            return View(blogs);
        }

        // GET: AuthorBlogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blogs blogs = db.Blogs.Find(id);
            if (blogs == null)
            {
                return HttpNotFound();
            }
            return View(blogs);
        }

        // POST: AuthorBlogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Blogs blogs = db.Blogs.Find(id);
            db.Blogs.Remove(blogs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/AuthorBlogs/Create.cshtml
@model Project.Models.Blogs
@using Project.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("Create", "AuthorBlogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    if (Session["AuthorID"] != null)
    {

        <div class="form-horizontal">
            <h4 class="col-md-2">Blog</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div>
                <div class="form-group">
                    <h5 class="col-md-2" style="display:inline-block">Yazar : @Session["name"].ToString()</h5>
                </div>
            </div>
            <div class="form-group">
                <h5 class="col-md-2">Başlık</h5>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <h5 class="col-md-2">Blog Yazısı</h5>
                <div class="col-md-10">
                    <textarea class="ckeditor" id="editor1"></textarea>
                    @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <h5 class="col-md-2">Blog Fotoğrafı</h5>
                <div class="col-md-10">
                    <input type="file" name="image" accept=".jpg,.jpeg,.png,.JPG.,JPEG" class="form-control" />
                    @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <label class="col-md-2">Kategori Seçiniz</label>
                    @if (ViewBag.category != null)
                    {
                        <select class="form-control" name="CategoryID">
                            @foreach (Categories item in ViewBag.category)
                            {
                                <option value="@item.CategoryID">@item.title</option>
                            }

                        </select>
                    }
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="padding: 1%;" >
                    <input type="submit" value="Paylaş" class="btn btn-success" />
                </div>
            </div>

        </div>
    }
}
<script src="https://cdn.ckeditor.com/ckeditor5/35.0.1/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#editor1'))
        .then(editor => {
            console.log(editor);
        })
        .catch(error => {
            console.error(error);
        });
</script>

Project/Views/AuthorBlogs/Delete.cshtml
@model Project.Models.Blogs

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blogs</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.blogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.blogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Views/AuthorBlogs/Details.cshtml
@model Project.Models.Blogs

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Blogs</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.blogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.blogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BlogID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Project/Views/AuthorBlogs/Edit.cshtml
@model Project.Models.Blogs

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Blogs</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogID)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorID, "AuthorID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.blogDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.blogDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.blogDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Project/Views/AuthorBlogs/Index.cshtml
@model IEnumerable<Project.Models.Blogs>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.blogDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authors.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categories.title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.blogDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Authors.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categories.title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BlogID }) |
            @Html.ActionLink("Details", "Details", new { id=item.BlogID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BlogID })
        </td>
    </tr>
}

</table>