Project/Controllers/AdminBlogController.cs
using Project.Models;
using System.Linq;
using System.Web.Mvc;
using System.IO;
using System.Web;
using System.Web.Helpers;
using System;
using System.Collections.Generic;

namespace Project.Controllers
{
    public class AdminBlogController : Controller
    {
        BLOGEntities db = new BLOGEntities();
        // GET: AdminBlog
        public ActionResult Index()

        {

            var blog = db.Blogs.ToList();
            return View(blog);
        }

        // GET: AdminBlog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            }

            Blogs blog = db.Blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();

            }
            return View(blog);
        }

        
        // GET: AdminBlog/Create
        public ActionResult Create()
        {
            ViewBag.category = db.Categories.ToList();
           
            return View();
        }

        // POST: AdminBlog/Create
        [HttpPost]
        public ActionResult Create(Blogs blog, HttpPostedFileBase image)
        {
            try
            {
                if (image != null)
                {
                    WebImage webImage = new WebImage(image.InputStream);
                    FileInfo fileInfo = new FileInfo(image.FileName);
                    string newImage = Guid.NewGuid().ToString() + fileInfo.Extension;
                    webImage.Resize(800, 350);
                    webImage.Save("~/Uploads/" + newImage);
                    blog.image = "/Uploads/" + newImage;
                }
                blog.blogDate = DateTime.Now;
                db.Blogs.Add(blog);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminBlog/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.category = db.Categories.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);

            }
            var blog = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: AdminBlog/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase image, Blogs blog)
        {
            try
            {
                var blogguncelle = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
                if (image != null)
                {

                    if (System.IO.File.Exists(Server.MapPath(blogguncelle.image)))
                    {
                        System.IO.File.Delete(Server.MapPath(blogguncelle.image));

                    }
                    WebImage webImage = new WebImage(image.InputStream);
                    FileInfo imageinfo = new FileInfo(image.FileName);
                    string newimage = Guid.NewGuid().ToString() + imageinfo.Extension;
                    webImage.Resize(800, 350);
                    webImage.Save("~/Uploads/" + newimage);
                    blogguncelle.image = "/Uploads/" + newimage;
                    blogguncelle.title = blog.title;
                    blogguncelle.text = blog.text;
                    blogguncelle.CategoryID = blog.CategoryID;
                    blogguncelle.AuthorID = blog.AuthorID;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminBlog/Delete/5
        public ActionResult Delete(int id)
        {
            var blog = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
            if(blog == null)
            {
                return HttpNotFound(); 
            }
            return View(blog);
        }

        // POST: AdminBlog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var blog = db.Blogs.Where(b => b.BlogID == id).SingleOrDefault();
                if (blog == null)
                {
                    return HttpNotFound();
                }
                if (System.IO.File.Exists(Server.MapPath(blog.image))){
                    System.IO.File.Exists(Server.MapPath(blog.image));
                };
                db.Blogs.Remove(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project/Views/AdminBlog/Create.cshtml
@model Project.Models.Blogs
@using Project.Models

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "AdminBlog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="image" accept=".jpg,.jpeg,.png,.JPG.,JPEG" class="form-control" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-10">
                <label>Kategori Seçiniz</label>
                @if (ViewBag.category != null)
                {
                    <select class="form-control" name="CategoryID">
                        @foreach (Categories item in ViewBag.category)
                        {
                            <option value="@item.CategoryID">@item.title</option>
                        }

                    </select>
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Yazar Seçiniz</label>
                @if (ViewBag.author != null)
                {
                    <select class="form-control" name="AuthorID">
                        @foreach (Authors item in ViewBag.author)
                        {
                            <option value="@item.AuthorID">@item.name</option>
                        }

                    </select>
                }
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Project/Views/AdminBlog/Delete.cshtml
@model Project.Models.Blogs
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img class="img-responsive" src="@Model.image" alt=".." width="60" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.blogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.blogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Project/Views/AdminBlog/Details.cshtml
@model Project.Models.Blogs

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div>
    <h2>Details</h2>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            <img class="img-responsive" src="@Model.image" alt=".." width="60" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.blogDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.blogDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Authors.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Authors.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categories.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.title)
        </dd>

    </dl>
    <p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.BlogID }) |
    @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Project/Views/AdminBlog/Edit.cshtml
@model Project.Models.Blogs
@using Project.Models

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "AdminBlog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Blog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.BlogID)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea class="ckeditor" id="editor1">
,
        </textarea>
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Eski", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img class="img-responsive" width="80" src="@Model.image" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img class="img-responsive" width="80" src="@Model.image" />
                <input type="file" name="image" accept=".jpg,.jpeg,.png,.JPG.,JPEG" class="form-control" />
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <label>Kategori Seçiniz</label>
                @if (ViewBag.category != null)
                {
                    <select class="form-control" name="CategoryID">

                        @foreach (Categories item in ViewBag.category)
                        {
                            <option value="@item.CategoryID">@item.title</option>
                        }

                    </select>
                }
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Project/Views/AdminBlog/Index.cshtml
@model IEnumerable<Project.Models.Blogs>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p>
    @Html.ActionLink("Yeni Blog Oluştur", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.blogDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authors.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categories.title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            <img class="img-responsive" width="20" src="@item.image" alt="Resim" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.blogDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Authors.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categories.title)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.BlogID }) |
            @Html.ActionLink("Detay", "Details", new { id=item.BlogID }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.BlogID })
        </td>
    </tr>
}

</table>